INSERT INTO course (name, description) VALUES ('Sample Course 1', 'Some sample course 1 description');
INSERT INTO course (name, description) VALUES ('Sample Course 2', 'Some sample course 2 description');
INSERT INTO problem (name, description) VALUES ('Problem A', 'Problem A description');
INSERT INTO problem (name, description) VALUES ('Problem B', 'Problem B description');
INSERT INTO problem (name, description) VALUES ('Problem C', 'Problem C description');
INSERT INTO problem (name, description) VALUES ('Problem D', 'Problem D description');
INSERT INTO problem (name, description) VALUES ('Problem E', 'Problem E description');
INSERT INTO test (problem_id, input, output) VALUES (1, 'Sample input 1', 'Sample output 1');
INSERT INTO test (problem_id, input, output) VALUES (2, 'Sample input 2', 'Sample output 2');
INSERT INTO test (problem_id, input, output) VALUES (3, 'Sample input 3', 'Sample output 3');
INSERT INTO test (problem_id, input, output) VALUES (4, 'Sample input 4', 'Sample output 4');
INSERT INTO test (problem_id, input, output) VALUES (5, 'Sample input 5', 'Sample output 5');
INSERT INTO course_problem (course_id, problem_id, ordinal_number) VALUES (1, 1, 1), (1, 5, 2), (1, 3, 3);
INSERT INTO course_problem (course_id, problem_id, ordinal_number) VALUES (2, 1, 1), (2, 2, 2), (2, 4, 3);